//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.UserAddresses = new HashSet<UserAddress>();
            this.Venues = new HashSet<Venue>();
            this.Businesses = new HashSet<Business>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Town { get; set; }
        public Nullable<int> CountyID { get; set; }
        public string Postcode { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
        public virtual ICollection<Venue> Venues { get; set; }
        public virtual ICollection<Business> Businesses { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
