//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public Conversation()
        {
            this.ConversationReplies = new HashSet<ConversationReply>();
        }
    
        public int ID { get; set; }
        public Nullable<int> User1ID { get; set; }
        public Nullable<int> User2ID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ConversationReply> ConversationReplies { get; set; }
    }
}
