//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public EventType()
        {
            this.EventType1 = new HashSet<EventType>();
            this.Events = new HashSet<Event>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> SubTypeID { get; set; }
    
        public virtual ICollection<EventType> EventType1 { get; set; }
        public virtual EventType EventType2 { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
