//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileType
    {
        public FileType()
        {
            this.FileType1 = new HashSet<FileType>();
            this.VenueFiles = new HashSet<VenueFile>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> SubTypeID { get; set; }
    
        public virtual ICollection<FileType> FileType1 { get; set; }
        public virtual FileType FileType2 { get; set; }
        public virtual ICollection<VenueFile> VenueFiles { get; set; }
    }
}
