//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryType
    {
        public GalleryType()
        {
            this.Galleries = new HashSet<Gallery>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> MaxSize { get; set; }
    
        public virtual ICollection<Gallery> Galleries { get; set; }
    }
}
