//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public Gallery()
        {
            this.GalleryImages = new HashSet<GalleryImage>();
            this.VenueGalleries = new HashSet<VenueGallery>();
            this.UserGalleries = new HashSet<UserGallery>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> GalleryTypeID { get; set; }
    
        public virtual GalleryType GalleryType { get; set; }
        public virtual ICollection<GalleryImage> GalleryImages { get; set; }
        public virtual ICollection<VenueGallery> VenueGalleries { get; set; }
        public virtual ICollection<UserGallery> UserGalleries { get; set; }
    }
}
