//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Venues = new HashSet<Venue>();
            this.GalleryImages = new HashSet<GalleryImage>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<Venue> Venues { get; set; }
        public virtual ICollection<GalleryImage> GalleryImages { get; set; }
    }
}
