//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicGenre
    {
        public MusicGenre()
        {
            this.MusicGenre1 = new HashSet<MusicGenre>();
            this.UserMusicGenres = new HashSet<UserMusicGenre>();
        }
    
        public int ID { get; set; }
        public string Genre { get; set; }
        public Nullable<int> SubGenreID { get; set; }
    
        public virtual ICollection<MusicGenre> MusicGenre1 { get; set; }
        public virtual MusicGenre MusicGenre2 { get; set; }
        public virtual ICollection<UserMusicGenre> UserMusicGenres { get; set; }
    }
}
