//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
            this.VenueProducts = new HashSet<VenueProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public Nullable<bool> RequiresDelivery { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<bool> Accept { get; set; }
        public Nullable<double> VATRate { get; set; }
        public string CustomerNotes { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<VenueProduct> VenueProducts { get; set; }
    }
}
