//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Conversations = new HashSet<Conversation>();
            this.ConversationReplies = new HashSet<ConversationReply>();
            this.UserStatus = new HashSet<UserStatu>();
        }
    
        public int ID { get; set; }
        public string Status1 { get; set; }
    
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual ICollection<ConversationReply> ConversationReplies { get; set; }
        public virtual ICollection<UserStatu> UserStatus { get; set; }
    }
}
