//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> SexualityID { get; set; }
        public Nullable<int> RelationshipStatusID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual RelationshipStatu RelationshipStatu { get; set; }
        public virtual SexualOrientation SexualOrientation { get; set; }
        public virtual User User { get; set; }
    }
}
