//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.Events = new HashSet<Event>();
            this.FavoriteVenues = new HashSet<FavoriteVenue>();
            this.VenueFeedbacks = new HashSet<VenueFeedback>();
            this.VenueInvitations = new HashSet<VenueInvitation>();
            this.VenueRatings = new HashSet<VenueRating>();
            this.VenueVisits = new HashSet<VenueVisit>();
            this.BusinessVenues = new HashSet<BusinessVenue>();
            this.VenueProducts = new HashSet<VenueProduct>();
            this.VenueFiles = new HashSet<VenueFile>();
            this.VenueGalleries = new HashSet<VenueGallery>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> VATno { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<FavoriteVenue> FavoriteVenues { get; set; }
        public virtual Image Image { get; set; }
        public virtual ICollection<VenueFeedback> VenueFeedbacks { get; set; }
        public virtual ICollection<VenueInvitation> VenueInvitations { get; set; }
        public virtual ICollection<VenueRating> VenueRatings { get; set; }
        public virtual ICollection<VenueVisit> VenueVisits { get; set; }
        public virtual VenueType VenueType { get; set; }
        public virtual ICollection<BusinessVenue> BusinessVenues { get; set; }
        public virtual ICollection<VenueProduct> VenueProducts { get; set; }
        public virtual ICollection<VenueFile> VenueFiles { get; set; }
        public virtual ICollection<VenueGallery> VenueGalleries { get; set; }
    }
}
