//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2R
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueVisit
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> VenueID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual NightStatu NightStatu { get; set; }
        public virtual User User { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
